FIXTURES = {
  simple_posts: JSON.parse(
    <<~'POST'
      { "posts": [
        {
          "id": "5f397fe1a185384852d1f1a5",
          "uuid": "e0110b84-63f2-4f0c-8a69-799c8d4d075e",
          "title": "Welcome to Ghost",
          "slug": "welcome",
          "html": "<h2 id=\"a-few-things-you-should-know\"><strong>A few things you should know</strong></h2><ol><li>Ghost is designed for ambitious, professional publishers who want to actively build a business around their content. That's who it works best for. </li><li>The entire platform can be modified and customised to suit your needs. It's very powerful, but does require some knowledge of code. Ghost is not necessarily a good platform for beginners or people who just want a simple personal blog. </li><li>It's possible to work with all your favourite tools and apps with hundreds of <a href=\"https://ghost.org/integrations/\">integrations</a> to speed up your workflows, connect email lists, build communities and much more.</li></ol><h2 id=\"behind-the-scenes\">Behind the scenes</h2><p>Ghost is made by an independent non-profit organisation called the Ghost Foundation. We are 100% self funded by revenue from our <a href=\"https://ghost.org/pricing\">Ghost(Pro)</a> service, and every penny we make is re-invested into funding further development of free, open source technology for modern publishing.</p><p>The version of Ghost you are looking at right now would not have been made possible without generous contributions from the open source <a href=\"https://github.com/TryGhost\">community</a>.</p><h2 id=\"next-up-the-editor\">Next up, the editor</h2><p>The main thing you'll want to read about next is probably: <a href=\"https://blog.spec.test/the-editor/\">the Ghost editor</a>. This is where the good stuff happens.</p><blockquote>By the way, once you're done reading, you can simply delete the default Ghost user from your team to remove all of these introductory posts! </blockquote>",
          "comment_id": "5f397fe1a185384852d1f1a5",
          "feature_image": "https://blog.spec.test/content/images/2020/08/babyyodaperf.gif",
          "featured": false,
          "visibility": "public",
          "send_email_when_published": false,
          "created_at": "2020-08-16T14:50:09.000-04:00",
          "updated_at": "2020-08-21T11:10:39.000-04:00",
          "published_at": "2020-08-16T14:50:15.000-04:00",
          "custom_excerpt": "Welcome, it's great to have you here.\nWe know that first impressions are important, so we've populated your new site with some initial getting started posts that will help you get familiar with everything in no time.",
          "codeinjection_head": null,
          "codeinjection_foot": null,
          "custom_template": null,
          "canonical_url": null,
          "url": "https://blog.spec.test/welcome/",
          "excerpt": "Welcome, it's great to have you here.\nWe know that first impressions are important, so we've populated your new site with some initial getting started posts that will help you get familiar with everything in no time.",
          "reading_time": 1,
          "access": true,
          "og_image": null,
          "og_title": null,
          "og_description": null,
          "twitter_image": null,
          "twitter_title": null,
          "twitter_description": null,
          "meta_title": null,
          "meta_description": null,
          "email_subject": null
        },
        {
          "id": "5f397fe1a185384852d1f1a3",
          "uuid": "fef883d3-6609-4bab-bafb-18f9f7b13b01",
          "title": "Writing posts with Ghost ✍️",
          "slug": "the-editor",
          "html": "<h2 id=\"just-start-writing\">Just start writing</h2><p>Ghost has a powerful visual editor with familiar formatting options, as well as the ability to add dynamic content.</p><p>Select your text to add formatting such as headers or to create links. Or use Markdown shortcuts to do the work for you - if that's your thing. </p><figure class=\"kg-card kg-image-card\"><img src=\"https://static.ghost.org/v2.0.0/images/formatting-editor-demo.gif\" class=\"kg-image\" alt></figure><h2 id=\"rich-editing-at-your-fingertips\">Rich editing at your fingertips</h2><p>The editor can also handle rich media objects, called <strong>cards</strong>, which can be organised and re-ordered using drag and drop. </p><p>You can insert a card either by clicking the  <code>+</code>  button, or typing  <code>/</code>  on a new line to search for a particular card. This allows you to efficiently insert<strong> images</strong>, <strong>markdown</strong>, <strong>html, embeds </strong>and more.</p><p><strong>For example</strong>:</p><ul><li>Insert a video from YouTube directly by pasting the URL</li><li>Create unique content like buttons or forms using the HTML card</li><li>Need to share some code? Embed code blocks directly </li></ul><pre><code>&lt;header class=\"site-header outer\"&gt;\n    &lt;div class=\"inner\"&gt;\n        {{&gt; \"site-nav\"}}\n    &lt;/div&gt;\n&lt;/header&gt;</code></pre><p>It's also possible to share links from across the web in a visual way using bookmark cards that automatically render information from a websites meta data. Paste any URL to try it out: </p><figure class=\"kg-card kg-bookmark-card\"><a class=\"kg-bookmark-container\" href=\"https://ghost.org/\"><div class=\"kg-bookmark-content\"><div class=\"kg-bookmark-title\">Ghost: The #1 open source headless Node.js CMS</div><div class=\"kg-bookmark-description\">The world’s most popular modern open source publishing platform. A headless Node.js CMS used by Apple, Sky News, Tinder and thousands more. MIT licensed, with 30k+ stars on Github.</div><div class=\"kg-bookmark-metadata\"><img class=\"kg-bookmark-icon\" src=\"https://ghost.org/icons/icon-512x512.png?v=188b8b6d743c6338ba2eab2e35bab4f5\"><span class=\"kg-bookmark-publisher\">Ghost</span></div></div><div class=\"kg-bookmark-thumbnail\"><img src=\"https://ghost.org/images/meta/Ghost.png\"></div></a></figure><h2 id=\"working-with-images-in-posts\">Working with images in posts</h2><p>You can add images to your posts in many ways:</p><ul><li>Upload from your computer</li><li>Click and drag an image into the browser</li><li>Paste directly into the editor from your clipboard</li><li>Insert using a URL</li></ul><h3 id=\"image-sizes\">Image sizes</h3><p>Once inserted you can blend images beautifully into your content at different sizes and add captions and alt tags wherever needed.</p><figure class=\"kg-card kg-image-card\"><img src=\"https://static.ghost.org/v3.0.0/images/image-sizes-ghost-editor.png\" class=\"kg-image\" alt></figure><h3 id=\"image-galleries\">Image galleries</h3><p>Tell visual stories using the gallery card to add up to 9 images that will display as a responsive image gallery: </p><figure class=\"kg-card kg-gallery-card kg-width-wide\"><div class=\"kg-gallery-container\"><div class=\"kg-gallery-row\"><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-1.jpg\" width=\"6000\" height=\"4000\" alt></div><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-2.jpg\" width=\"5746\" height=\"3831\" alt></div><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-3.jpg\" width=\"5872\" height=\"3915\" alt></div></div></div></figure><h3 id=\"image-optimisation\">Image optimisation</h3><p>Ghost will automatically resize and optimise your images with lossless compression. Your posts will be fully optimised for the web without any extra effort on your part.</p><h2 id=\"next-publishing-options\">Next: Publishing Options</h2><p>Once your post is looking good, you'll want to use the <a href=\"https://blog.spec.test/publishing-options/\">publishing options</a> to ensure it gets distributed in the right places, with custom meta data, feature images and more.</p>",
          "comment_id": "5f397fe1a185384852d1f1a3",
          "feature_image": "https://static.ghost.org/v3.0.0/images/writing-posts-with-ghost.png",
          "featured": false,
          "visibility": "public",
          "send_email_when_published": false,
          "created_at": "2020-08-16T14:50:09.000-04:00",
          "updated_at": "2020-08-16T14:50:09.000-04:00",
          "published_at": "2020-08-16T14:50:14.000-04:00",
          "custom_excerpt": "Discover familiar formatting options in a functional toolbar and the ability to add dynamic content seamlessly.",
          "codeinjection_head": null,
          "codeinjection_foot": null,
          "custom_template": null,
          "canonical_url": null,
          "url": "https://blog.spec.test/the-editor/",
          "excerpt": "Discover familiar formatting options in a functional toolbar and the ability to add dynamic content seamlessly.",
          "reading_time": 3,
          "access": true,
          "og_image": null,
          "og_title": null,
          "og_description": null,
          "twitter_image": null,
          "twitter_title": null,
          "twitter_description": null,
          "meta_title": null,
          "meta_description": null,
          "email_subject": null
        }
      ],
        "meta": {
          "pagination": {
            "page": 1,
            "limit": 15,
            "pages": 1,
            "total": 8,
            "next": null,
            "prev": null
          }
        }}
    POST
  ),
  posts_with_tags: JSON.parse(
    <<~'POST'
      {
        "posts": [
          {
            "id": "5f397fe1a185384852d1f1a5",
            "uuid": "e0110b84-63f2-4f0c-8a69-799c8d4d075e",
            "title": "Welcome to Ghost",
            "slug": "welcome",
            "html": "<h2 id=\"a-few-things-you-should-know\"><strong>A few things you should know</strong></h2><ol><li>Ghost is designed for ambitious, professional publishers who want to actively build a business around their content. That's who it works best for. </li><li>The entire platform can be modified and customised to suit your needs. It's very powerful, but does require some knowledge of code. Ghost is not necessarily a good platform for beginners or people who just want a simple personal blog. </li><li>It's possible to work with all your favourite tools and apps with hundreds of <a href=\"https://ghost.org/integrations/\">integrations</a> to speed up your workflows, connect email lists, build communities and much more.</li></ol><h2 id=\"behind-the-scenes\">Behind the scenes</h2><p>Ghost is made by an independent non-profit organisation called the Ghost Foundation. We are 100% self funded by revenue from our <a href=\"https://ghost.org/pricing\">Ghost(Pro)</a> service, and every penny we make is re-invested into funding further development of free, open source technology for modern publishing.</p><p>The version of Ghost you are looking at right now would not have been made possible without generous contributions from the open source <a href=\"https://github.com/TryGhost\">community</a>.</p><h2 id=\"next-up-the-editor\">Next up, the editor</h2><p>The main thing you'll want to read about next is probably: <a href=\"https://blog.spec.test/the-editor/\">the Ghost editor</a>. This is where the good stuff happens.</p><blockquote>By the way, once you're done reading, you can simply delete the default Ghost user from your team to remove all of these introductory posts! </blockquote>",
            "comment_id": "5f397fe1a185384852d1f1a5",
            "feature_image": "https://blog.spec.test/content/images/2020/08/babyyodaperf.gif",
            "featured": false,
            "visibility": "public",
            "send_email_when_published": false,
            "created_at": "2020-08-16T14:50:09.000-04:00",
            "updated_at": "2020-08-21T11:10:39.000-04:00",
            "published_at": "2020-08-16T14:50:15.000-04:00",
            "custom_excerpt": "Welcome, it's great to have you here.\nWe know that first impressions are important, so we've populated your new site with some initial getting started posts that will help you get familiar with everything in no time.",
            "codeinjection_head": null,
            "codeinjection_foot": null,
            "custom_template": null,
            "canonical_url": null,
            "tags": [
              {
                "id": "5f397fe0a185384852d1f144",
                "name": "Getting Started",
                "slug": "getting-started",
                "description": null,
                "feature_image": null,
                "visibility": "public",
                "og_image": null,
                "og_title": null,
                "og_description": null,
                "twitter_image": null,
                "twitter_title": null,
                "twitter_description": null,
                "meta_title": null,
                "meta_description": null,
                "codeinjection_head": null,
                "codeinjection_foot": null,
                "canonical_url": null,
                "accent_color": null,
                "url": "https://blog.spec.test/tag/getting-started/"
              }
            ],
            "primary_tag": {
              "id": "5f397fe0a185384852d1f144",
              "name": "Getting Started",
              "slug": "getting-started",
              "description": null,
              "feature_image": null,
              "visibility": "public",
              "og_image": null,
              "og_title": null,
              "og_description": null,
              "twitter_image": null,
              "twitter_title": null,
              "twitter_description": null,
              "meta_title": null,
              "meta_description": null,
              "codeinjection_head": null,
              "codeinjection_foot": null,
              "canonical_url": null,
              "accent_color": null,
              "url": "https://blog.spec.test/tag/getting-started/"
            },
            "url": "https://blog.spec.test/welcome/",
            "excerpt": "Welcome, it's great to have you here.\nWe know that first impressions are important, so we've populated your new site with some initial getting started posts that will help you get familiar with everything in no time.",
            "reading_time": 1,
            "access": true,
            "og_image": null,
            "og_title": null,
            "og_description": null,
            "twitter_image": null,
            "twitter_title": null,
            "twitter_description": null,
            "meta_title": null,
            "meta_description": null,
            "email_subject": null
          },
          {
            "id": "5f397fe1a185384852d1f1a3",
            "uuid": "fef883d3-6609-4bab-bafb-18f9f7b13b01",
            "title": "Writing posts with Ghost ✍️",
            "slug": "the-editor",
            "html": "<h2 id=\"just-start-writing\">Just start writing</h2><p>Ghost has a powerful visual editor with familiar formatting options, as well as the ability to add dynamic content.</p><p>Select your text to add formatting such as headers or to create links. Or use Markdown shortcuts to do the work for you - if that's your thing. </p><figure class=\"kg-card kg-image-card\"><img src=\"https://static.ghost.org/v2.0.0/images/formatting-editor-demo.gif\" class=\"kg-image\" alt></figure><h2 id=\"rich-editing-at-your-fingertips\">Rich editing at your fingertips</h2><p>The editor can also handle rich media objects, called <strong>cards</strong>, which can be organised and re-ordered using drag and drop. </p><p>You can insert a card either by clicking the  <code>+</code>  button, or typing  <code>/</code>  on a new line to search for a particular card. This allows you to efficiently insert<strong> images</strong>, <strong>markdown</strong>, <strong>html, embeds </strong>and more.</p><p><strong>For example</strong>:</p><ul><li>Insert a video from YouTube directly by pasting the URL</li><li>Create unique content like buttons or forms using the HTML card</li><li>Need to share some code? Embed code blocks directly </li></ul><pre><code>&lt;header class=\"site-header outer\"&gt;\n    &lt;div class=\"inner\"&gt;\n        {{&gt; \"site-nav\"}}\n    &lt;/div&gt;\n&lt;/header&gt;</code></pre><p>It's also possible to share links from across the web in a visual way using bookmark cards that automatically render information from a websites meta data. Paste any URL to try it out: </p><figure class=\"kg-card kg-bookmark-card\"><a class=\"kg-bookmark-container\" href=\"https://ghost.org/\"><div class=\"kg-bookmark-content\"><div class=\"kg-bookmark-title\">Ghost: The #1 open source headless Node.js CMS</div><div class=\"kg-bookmark-description\">The world’s most popular modern open source publishing platform. A headless Node.js CMS used by Apple, Sky News, Tinder and thousands more. MIT licensed, with 30k+ stars on Github.</div><div class=\"kg-bookmark-metadata\"><img class=\"kg-bookmark-icon\" src=\"https://ghost.org/icons/icon-512x512.png?v=188b8b6d743c6338ba2eab2e35bab4f5\"><span class=\"kg-bookmark-publisher\">Ghost</span></div></div><div class=\"kg-bookmark-thumbnail\"><img src=\"https://ghost.org/images/meta/Ghost.png\"></div></a></figure><h2 id=\"working-with-images-in-posts\">Working with images in posts</h2><p>You can add images to your posts in many ways:</p><ul><li>Upload from your computer</li><li>Click and drag an image into the browser</li><li>Paste directly into the editor from your clipboard</li><li>Insert using a URL</li></ul><h3 id=\"image-sizes\">Image sizes</h3><p>Once inserted you can blend images beautifully into your content at different sizes and add captions and alt tags wherever needed.</p><figure class=\"kg-card kg-image-card\"><img src=\"https://static.ghost.org/v3.0.0/images/image-sizes-ghost-editor.png\" class=\"kg-image\" alt></figure><h3 id=\"image-galleries\">Image galleries</h3><p>Tell visual stories using the gallery card to add up to 9 images that will display as a responsive image gallery: </p><figure class=\"kg-card kg-gallery-card kg-width-wide\"><div class=\"kg-gallery-container\"><div class=\"kg-gallery-row\"><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-1.jpg\" width=\"6000\" height=\"4000\" alt></div><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-2.jpg\" width=\"5746\" height=\"3831\" alt></div><div class=\"kg-gallery-image\"><img src=\"https://static.ghost.org/v3.0.0/images/gallery-sample-3.jpg\" width=\"5872\" height=\"3915\" alt></div></div></div></figure><h3 id=\"image-optimisation\">Image optimisation</h3><p>Ghost will automatically resize and optimise your images with lossless compression. Your posts will be fully optimised for the web without any extra effort on your part.</p><h2 id=\"next-publishing-options\">Next: Publishing Options</h2><p>Once your post is looking good, you'll want to use the <a href=\"https://blog.spec.test/publishing-options/\">publishing options</a> to ensure it gets distributed in the right places, with custom meta data, feature images and more.</p>",
            "comment_id": "5f397fe1a185384852d1f1a3",
            "feature_image": "https://static.ghost.org/v3.0.0/images/writing-posts-with-ghost.png",
            "featured": false,
            "visibility": "public",
            "send_email_when_published": false,
            "created_at": "2020-08-16T14:50:09.000-04:00",
            "updated_at": "2020-08-16T14:50:09.000-04:00",
            "published_at": "2020-08-16T14:50:14.000-04:00",
            "custom_excerpt": "Discover familiar formatting options in a functional toolbar and the ability to add dynamic content seamlessly.",
            "codeinjection_head": null,
            "codeinjection_foot": null,
            "custom_template": null,
            "canonical_url": null,
            "tags": [
              {
                "id": "5f397fe0a185384852d1f144",
                "name": "Getting Started",
                "slug": "getting-started",
                "description": null,
                "feature_image": null,
                "visibility": "public",
                "og_image": null,
                "og_title": null,
                "og_description": null,
                "twitter_image": null,
                "twitter_title": null,
                "twitter_description": null,
                "meta_title": null,
                "meta_description": null,
                "codeinjection_head": null,
                "codeinjection_foot": null,
                "canonical_url": null,
                "accent_color": null,
                "url": "https://blog.spec.test/tag/getting-started/"
              }
            ],
            "primary_tag": {
              "id": "5f397fe0a185384852d1f144",
              "name": "Getting Started",
              "slug": "getting-started",
              "description": null,
              "feature_image": null,
              "visibility": "public",
              "og_image": null,
              "og_title": null,
              "og_description": null,
              "twitter_image": null,
              "twitter_title": null,
              "twitter_description": null,
              "meta_title": null,
              "meta_description": null,
              "codeinjection_head": null,
              "codeinjection_foot": null,
              "canonical_url": null,
              "accent_color": null,
              "url": "https://blog.spec.test/tag/getting-started/"
            },
            "url": "https://blog.spec.test/the-editor/",
            "excerpt": "Discover familiar formatting options in a functional toolbar and the ability to add dynamic content seamlessly.",
            "reading_time": 3,
            "access": true,
            "og_image": null,
            "og_title": null,
            "og_description": null,
            "twitter_image": null,
            "twitter_title": null,
            "twitter_description": null,
            "meta_title": null,
            "meta_description": null,
            "email_subject": null
          }
        ],
        "meta": {
          "pagination": {
            "page": 1,
            "limit": 15,
            "pages": 1,
            "total": 8,
            "next": null,
            "prev": null
          }
        }
      }
    POST
  ),
  posts_with_authors: JSON.parse(
    <<~'POST'
      {
        "posts": [
          {
            "id": "5f4005a8a185384852d1f2db",
            "uuid": "259fb76d-e92e-4f94-8e93-3b90ef448251",
            "title": "This is my first blog post",
            "slug": "this-is-my-first-blog-post",
            "html": "<blockquote>Hey there, this is a formatted blog post body.</blockquote>",
            "comment_id": "5f4005a8a185384852d1f2db",
            "feature_image": null,
            "featured": true,
            "visibility": "public",
            "send_email_when_published": false,
            "created_at": "2020-08-21T13:34:32.000-04:00",
            "updated_at": "2020-08-21T15:05:31.000-04:00",
            "published_at": "2020-08-21T15:05:27.000-04:00",
            "custom_excerpt": null,
            "codeinjection_head": null,
            "codeinjection_foot": null,
            "custom_template": null,
            "canonical_url": null,
            "authors": [
              {
                "id": "1",
                "name": "Georges Gabereau",
                "slug": "georges",
                "profile_image": null,
                "cover_image": null,
                "bio": null,
                "website": null,
                "location": null,
                "facebook": null,
                "twitter": null,
                "meta_title": null,
                "meta_description": null,
                "url": "https://blog.spec.test/author/georges/"
              }
            ],
            "primary_author": {
              "id": "1",
              "name": "Georges Gabereau",
              "slug": "georges",
              "profile_image": null,
              "cover_image": null,
              "bio": null,
              "website": null,
              "location": null,
              "facebook": null,
              "twitter": null,
              "meta_title": null,
              "meta_description": null,
              "url": "https://blog.spec.test/author/georges/"
            },
            "url": "https://blog.spec.test/this-is-my-first-blog-post/",
            "excerpt": "> Hey there, this is a formatted blog post body.",
            "reading_time": 0,
            "access": true,
            "og_image": null,
            "og_title": null,
            "og_description": null,
            "twitter_image": null,
            "twitter_title": null,
            "twitter_description": null,
            "meta_title": null,
            "meta_description": null,
            "email_subject": null
          }
        ],
        "meta": {
          "pagination": {
            "page": 1,
            "limit": 15,
            "pages": 1,
            "total": 8,
            "next": null,
            "prev": null
          }
        }
      }
    POST
  )
}.freeze
